// Copyright 2026 GAIA Contributors
//
// Licensed under the MIT License.
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://opensource.org/licenses/MIT
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package core

import (
	"bytes"
	"encoding/json"
	"fmt"
	"log/slog"
	"net/http"
	"time"

	"gaia/kernel/pkg/types"
)

// Planner defines the interface for the probabilistic reasoning engine of GAIA.
// By abstracting the planner, we ensure the Control Loop remains deterministic
// and agnostic to whether the plan is generated by a local or cloud LLM.
type Planner interface {
	// GeneratePlan takes a user goal and current state and returns a structured DAG of steps.
	GeneratePlan(goal string, state map[string]interface{}, capabilities []types.Capability) (*types.PlanRecord, error)
	
	// Complete performs a simple text-to-text completion.
	Complete(prompt string) (string, error)
	
	// Vision performs a vision-to-text analysis using an image.
	Vision(prompt string, imageBase64 string) (string, error)
}

// LocalLLMPlanner is an adapter for locally hosted LLM engines like Ollama or Llama.cpp.
type LocalLLMPlanner struct {
	Endpoint string
	Model    string
}

// GeneratePlan for LocalLLMPlanner implements the Ollama API (/api/generate) to fetch a JSON plan.
func (p *LocalLLMPlanner) GeneratePlan(goal string, state map[string]interface{}, capabilities []types.Capability) (*types.PlanRecord, error) {
	slog.Debug("Intelligence: Local Plan Generation", "model", p.Model)
	userPrompt, err := BuildUserPrompt(goal, state, capabilities)
	if err != nil {
		return nil, err
	}

	reqBody := map[string]interface{}{
		"model":  p.Model,
		"system": SystemPrompt,
		"prompt": userPrompt,
		"stream": false,
		"format": "json",
	}

	bodyBytes, _ := json.Marshal(reqBody)
	req, err := http.NewRequest("POST", p.Endpoint, bytes.NewBuffer(bodyBytes))
	if err != nil {
		return nil, fmt.Errorf("core: failed to create ollama request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")

	client := &http.Client{Timeout: 300 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		slog.Error("Local LLM connection failed", "error", err)
		return nil, fmt.Errorf("core: %w: local llm request failed: %v", fmt.Errorf(string(types.ErrorCodeInternalError)), err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		slog.Warn("Local LLM returned non-200", "status", resp.StatusCode)
		return nil, fmt.Errorf("core: local llm returned status %d", resp.StatusCode)
	}

	var ollamaResp struct {
		Response string `json:"response"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&ollamaResp); err != nil {
		return nil, fmt.Errorf("core: failed to decode ollama response: %w", err)
	}

	return parsePlanJSON(ollamaResp.Response)
}

func (p *LocalLLMPlanner) Complete(prompt string) (string, error) {
	slog.Info("LLM Proxy: Local Completion", "model", p.Model)
	reqBody := map[string]interface{}{
		"model":  p.Model,
		"prompt": prompt,
		"stream": false,
	}

	bodyBytes, _ := json.Marshal(reqBody)
	resp, err := http.Post(p.Endpoint, "application/json", bytes.NewBuffer(bodyBytes))
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	var ollamaResp struct {
		Response string `json:"response"`
	}
	json.NewDecoder(resp.Body).Decode(&ollamaResp)
	return ollamaResp.Response, nil
}

func (p *LocalLLMPlanner) Vision(prompt string, imageBase64 string) (string, error) {
	slog.Info("LLM Proxy: Local Vision", "model", p.Model)
	reqBody := map[string]interface{}{
		"model":  p.Model,
		"prompt": prompt,
		"images": []string{imageBase64},
		"stream": false,
	}

	bodyBytes, _ := json.Marshal(reqBody)
	resp, err := http.Post(p.Endpoint, "application/json", bytes.NewBuffer(bodyBytes))
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	var ollamaResp struct {
		Response string `json:"response"`
	}
	json.NewDecoder(resp.Body).Decode(&ollamaResp)
	return ollamaResp.Response, nil
}

// CloudLLMPlanner is an adapter for managed cloud providers like OpenAI or Anthropic.
type CloudLLMPlanner struct {
	Endpoint string
	Model    string
	APIKey   string
}

// GeneratePlan for CloudLLMPlanner implements the OpenAI chat completions API.
func (p *CloudLLMPlanner) GeneratePlan(goal string, state map[string]interface{}, capabilities []types.Capability) (*types.PlanRecord, error) {
	userPrompt, err := BuildUserPrompt(goal, state, capabilities)
	if err != nil {
		return nil, err
	}

	reqBody := map[string]interface{}{
		"model": p.Model,
		"messages": []map[string]string{
			{"role": "system", "content": SystemPrompt},
			{"role": "user", "content": userPrompt},
		},
		"response_format": map[string]string{"type": "json_object"},
	}

	bodyBytes, _ := json.Marshal(reqBody)
	req, err := http.NewRequest("POST", p.Endpoint, bytes.NewBuffer(bodyBytes))
	if err != nil {
		return nil, fmt.Errorf("core: failed to create openai request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+p.APIKey)

	client := &http.Client{Timeout: 60 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("core: %w: cloud llm request failed: %v", fmt.Errorf(string(types.ErrorCodeInternalError)), err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("core: cloud llm returned status %d", resp.StatusCode)
	}

	var openaiResp struct {
		Choices []struct {
			Message struct {
				Content string `json:"content"`
			} `json:"message"`
		} `json:"choices"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&openaiResp); err != nil {
		return nil, fmt.Errorf("core: failed to decode cloud llm response: %w", err)
	}

	if len(openaiResp.Choices) == 0 {
		return nil, fmt.Errorf("core: cloud llm returned zero choices")
	}

	return parsePlanJSON(openaiResp.Choices[0].Message.Content)
}

func (p *CloudLLMPlanner) Complete(prompt string) (string, error) {
	slog.Info("LLM Proxy: Cloud Completion", "model", p.Model)
	reqBody := map[string]interface{}{
		"model": p.Model,
		"messages": []map[string]string{
			{"role": "user", "content": prompt},
		},
	}

	bodyBytes, _ := json.Marshal(reqBody)
	req, _ := http.NewRequest("POST", p.Endpoint, bytes.NewBuffer(bodyBytes))
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+p.APIKey)

	client := &http.Client{Timeout: 60 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	var openaiResp struct {
		Choices []struct {
			Message struct {
				Content string `json:"content"`
			} `json:"message"`
		} `json:"choices"`
	}
	json.NewDecoder(resp.Body).Decode(&openaiResp)
	if len(openaiResp.Choices) == 0 {
		return "", fmt.Errorf("openai: zero choices")
	}
	return openaiResp.Choices[0].Message.Content, nil
}

func (p *CloudLLMPlanner) Vision(prompt string, imageBase64 string) (string, error) {
	slog.Info("LLM Proxy: Cloud Vision", "model", p.Model)
	reqBody := map[string]interface{}{
		"model": p.Model,
		"messages": []interface{}{
			map[string]interface{}{
				"role": "user",
				"content": []interface{}{
					map[string]string{"type": "text", "text": prompt},
					map[string]interface{}{
						"type": "image_url",
						"image_url": map[string]string{
							"url": fmt.Sprintf("data:image/jpeg;base64,%s", imageBase64),
						},
					},
				},
			},
		},
	}

	bodyBytes, _ := json.Marshal(reqBody)
	req, _ := http.NewRequest("POST", p.Endpoint, bytes.NewBuffer(bodyBytes))
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+p.APIKey)

	client := &http.Client{Timeout: 60 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	var openaiResp struct {
		Choices []struct {
			Message struct {
				Content string `json:"content"`
			} `json:"message"`
		} `json:"choices"`
	}
	json.NewDecoder(resp.Body).Decode(&openaiResp)
	if len(openaiResp.Choices) == 0 {
		return "", fmt.Errorf("openai: zero choices")
	}
	return openaiResp.Choices[0].Message.Content, nil
}

// parsePlanJSON is a helper to unmarshal the raw JSON string from the LLM into a PlanRecord.
func parsePlanJSON(raw string) (*types.PlanRecord, error) {
	var record types.PlanRecord
	if err := json.Unmarshal([]byte(raw), &record); err != nil {
		return nil, fmt.Errorf("core: %w: failed to parse llm json: %v", fmt.Errorf(string(types.ErrorCodeSchemaViolation)), err)
	}
	
	// Default statuses for new steps
	for i := range record.Steps {
		record.Steps[i].Status = types.StepStatusPending
	}
	record.Status = types.PlanStatusValid
	
	return &record, nil
}

// NewPlanner is a factory function that injects the correct planner implementation.
func NewPlanner(config *KernelConfig) (Planner, error) {
	switch config.PlannerProvider {
	case LLMProviderLocal:
		return &LocalLLMPlanner{Endpoint: config.PlannerEndpoint, Model: config.PlannerModel}, nil
	case LLMProviderCloud:
		return &CloudLLMPlanner{Endpoint: config.PlannerEndpoint, Model: config.PlannerModel, APIKey: config.PlannerAPIKey}, nil
	default:
		return nil, fmt.Errorf("core: unsupported planner provider: %s", config.PlannerProvider)
	}
}
