// Copyright 2026 GAIA Contributors
//
// Licensed under the MIT License.
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://opensource.org/licenses/MIT
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package core

import (
	"fmt"
	"gaia/kernel/pkg/types"
)

// Planner defines the interface for the probabilistic reasoning engine of GAIA.
// By abstracting the planner, we ensure the Control Loop remains deterministic
// and agnostic to whether the plan is generated by a local or cloud LLM.
type Planner interface {
	// GeneratePlan takes a user goal and current state and returns a structured DAG of steps.
	// It implements the "Probabilistic" side of the GAIA equation.
	GeneratePlan(goal string, state map[string]interface{}, capabilities []types.Capability) (*types.PlanRecord, error)
}

// LocalLLMPlanner is an adapter for locally hosted LLM engines like Ollama or Llama.cpp.
type LocalLLMPlanner struct {
	Endpoint string
}

// GeneratePlan for LocalLLMPlanner will eventually implement the specific JSON
// prompting and parsing logic for local models.
func (p *LocalLLMPlanner) GeneratePlan(goal string, state map[string]interface{}, capabilities []types.Capability) (*types.PlanRecord, error) {
	// TODO: Implement Phase 3 (Runtime) network logic for Ollama/Local LLM.
	return nil, fmt.Errorf("core: local planner not yet implemented in foundation phase")
}

// CloudLLMPlanner is an adapter for managed cloud providers like OpenAI or Anthropic.
type CloudLLMPlanner struct {
	Endpoint string
	APIKey   string
}

// GeneratePlan for CloudLLMPlanner will eventually implement the specific
// chat-completion API logic for cloud providers.
func (p *CloudLLMPlanner) GeneratePlan(goal string, state map[string]interface{}, capabilities []types.Capability) (*types.PlanRecord, error) {
	// TODO: Implement Phase 3 (Runtime) network logic for OpenAI/Anthropic.
	return nil, fmt.Errorf("core: cloud planner not yet implemented in foundation phase")
}

// NewPlanner is a factory function that injects the correct planner implementation
// based on the dynamic KernelConfig. This ensures zero hardcoded logic.
func NewPlanner(config *KernelConfig) (Planner, error) {
	switch config.PlannerProvider {
	case LLMProviderLocal:
		return &LocalLLMPlanner{Endpoint: config.PlannerEndpoint}, nil
	case LLMProviderCloud:
		return &CloudLLMPlanner{Endpoint: config.PlannerEndpoint, APIKey: config.PlannerAPIKey}, nil
	default:
		return nil, fmt.Errorf("core: unsupported planner provider: %s", config.PlannerProvider)
	}
}
