# generated by datamodel-codegen:
#   filename:  agent-manifest.json
#   timestamp: 2026-04-25T13:57:36+00:00

from __future__ import annotations

from typing import Any, Optional

from pydantic import BaseModel, Extra


class AuthConfig(BaseModel):
    class Config:
        extra = Extra.allow

    type: str
    secret_ref: Optional[str] = None
    scopes: Optional[list[str]] = None


class Constraints(BaseModel):
    class Config:
        extra = Extra.allow

    read_only: bool
    mutates_state: bool
    external_io: bool


class HealthEndpointSpec(BaseModel):
    class Config:
        extra = Extra.allow

    method: str
    expected_response: Optional[dict[str, Any]] = None
    timeout_ms: int


class InvokeContract(BaseModel):
    class Config:
        extra = Extra.allow

    timeout_ms: int
    async_supported: bool


class StateRequirements(BaseModel):
    class Config:
        extra = Extra.allow

    required: bool
    max_bytes: Optional[int] = None


class Capability(BaseModel):
    class Config:
        extra = Extra.allow

    name: str
    description: str
    input_schema: dict[str, Any]
    output_schema: dict[str, Any]
    idempotent: bool
    constraints: Optional[Constraints] = None


class AgentManifest(BaseModel):
    class Config:
        extra = Extra.allow

    agent_id: str
    version: str
    transport: str
    protocol: str
    endpoint: str
    health_endpoint: Optional[str] = None
    health_endpoint_spec: Optional[HealthEndpointSpec] = None
    invoke: InvokeContract
    capabilities: list[Capability]
    auth: Optional[AuthConfig] = None
    state_requirements: Optional[StateRequirements] = None


class Model(BaseModel):
    class Config:
        extra = Extra.allow

    __root__: AgentManifest
