# generated by datamodel-codegen:
#   filename:  async-completion.json
#   timestamp: 2026-04-25T13:57:36+00:00

from __future__ import annotations

from typing import Any, Optional

from pydantic import BaseModel, Extra


class Error(BaseModel):
    class Config:
        extra = Extra.allow

    code: str
    message: str
    retryable: bool
    details: Optional[dict[str, Any]] = None


class AsyncCompletion(BaseModel):
    class Config:
        extra = Extra.allow

    type: str
    job_id: str
    request_id: str
    success: bool
    output: Optional[Any] = None
    error: Optional[Error] = None


class Model(BaseModel):
    class Config:
        extra = Extra.allow

    __root__: AsyncCompletion
