# generated by datamodel-codegen:
#   filename:  event.json
#   timestamp: 2026-04-25T13:57:36+00:00

from __future__ import annotations

from datetime import datetime
from typing import Any, Optional

from pydantic import BaseModel, Extra


class Event(BaseModel):
    class Config:
        extra = Extra.allow

    type: str
    name: str
    payload: Optional[dict[str, Any]] = None
    task_id: Optional[str] = None
    step_id: Optional[str] = None
    timestamp: datetime
    sequence_number: Optional[int] = None
    previous_event_id: Optional[str] = None


class Model(BaseModel):
    class Config:
        extra = Extra.allow

    __root__: Event
