# generated by datamodel-codegen:
#   filename:  request.json
#   timestamp: 2026-04-25T13:57:36+00:00

from __future__ import annotations

from typing import Any, Optional

from pydantic import BaseModel, Extra, Field


class Request(BaseModel):
    class Config:
        extra = Extra.allow

    type: str
    request_id: str
    from_: str = Field(..., alias='from')
    task_id: str
    step_id: str
    capability: str
    input: Any
    mode: str
    timeout_ms: Optional[int] = None


class Model(BaseModel):
    class Config:
        extra = Extra.allow

    __root__: Request
