# generated by datamodel-codegen:
#   filename:  response.json
#   timestamp: 2026-04-25T13:57:36+00:00

from __future__ import annotations

from typing import Any, Optional

from pydantic import BaseModel, Extra


class Error(BaseModel):
    class Config:
        extra = Extra.allow

    code: str
    message: str
    retryable: bool
    details: Optional[dict[str, Any]] = None


class RequestMetrics(BaseModel):
    class Config:
        extra = Extra.allow

    duration_ms: Optional[int] = None
    cost_estimate: Optional[float] = None
    tokens_used: Optional[int] = None


class Response(BaseModel):
    class Config:
        extra = Extra.allow

    request_id: str
    success: bool
    output: Optional[Any] = None
    error: Optional[Error] = None
    job_id: Optional[str] = None
    metrics: Optional[RequestMetrics] = None


class Model(BaseModel):
    class Config:
        extra = Extra.allow

    __root__: Response
