# generated by datamodel-codegen:
#   filename:  task.json
#   timestamp: 2026-04-25T13:57:36+00:00

from __future__ import annotations

from datetime import datetime
from typing import Any, Optional

from pydantic import BaseModel, Extra


class Error(BaseModel):
    class Config:
        extra = Extra.allow

    code: str
    message: str
    retryable: bool
    details: Optional[dict[str, Any]] = None


class Step(BaseModel):
    class Config:
        extra = Extra.allow

    step_id: str
    capability: str
    input: Any
    depends_on: Optional[list[str]] = None
    status: str
    job_id: Optional[str] = None
    async_timeout_ms: Optional[int] = None
    assigned_agent: Optional[str] = None
    output: Optional[Any] = None
    output_schema: Optional[dict[str, Any]] = None
    error: Optional[Error] = None
    retry_count: int


class Task(BaseModel):
    class Config:
        extra = Extra.allow

    task_id: str
    goal: str
    status: str
    plan: Optional[list[Step]] = None
    current_step: int
    metadata: Optional[dict[str, Any]] = None
    created_at: datetime
    updated_at: datetime
    finished_at: Optional[datetime] = None


class Model(BaseModel):
    class Config:
        extra = Extra.allow

    __root__: Task
